name: "Terraform - Features"
on:
  push:
    branches-ignore:
      - main
      - uat
      - dev

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        component-path: 
          [ 
            "100-app-infra/110-terraform-state",
            "100-app-infra/120-network",
            "100-app-infra/130-cicd-agent",
            "100-app-infra/140-vault-instance",
            "100-app-infra/150-security-groups", 
            "100-app-infra/160-data-base", 
            "100-app-infra/170-instances" 
            ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8
      
      - name: Terraform Format
        working-directory: ${{ matrix.component-path }}
        run: terraform fmt -check
        
      - name: Terraform Init
        working-directory: ${{ matrix.component-path }}
        run: terraform init  -backend-config=../vars/backend_config.hcl

      - name: Terraform Validate
        working-directory: ${{ matrix.component-path }}
        run: terraform validate -no-color
